[tool.poetry]
name = "AECPy"
version = "0.0.1"
description = "Analise estrutural basado no metodo da rigidez direta"
authors = ["Felipe Schaedler de Almeida <felipe.alemida@ufrgs.br>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/schaedleralmeida/AECPy"
repository = "https://github.com/schaedleralmeida/AECPy"
packages = [{ include = "AECPy", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
numpy = "*"
pandas = "*"
matplotlib = "*"
openpyxl = "*"
odfpy = "*"

[tool.poetry.group.dev.dependencies]
pytest = "*"
ruff = "*"
ipykernel = "^7.2.0"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"